### ISSUE TITLE
Инфраструктура

### ISSUE THREAD

**Issue by npc109** [bcrypto/bee2#1]
Не подскажите, существуют ли библитеки/форки библиотек  для создания электронных подписей с этими элгоритмами. Может быть какие-нибудь либы для подписи пдф  ?

**Comment by agievich** [comment]
Во-первых, в этом репозитории размещена экспериментальная редакция Bee2. Актуальную редакцию можно найти вот здесь: https://github.com/agievich/bee2.

Во-вторых, Bee2 -- это криптоядро. Управление форматами, в частности расширенными подписями (см. https://github.com/bcrypto/stb/tree/master/34.101.80), находится вне проблемного поля Bee2. 

Частично вопросы управления форматами решаются с помощью библиотеки [Bee2evp](https://github.com/bcrypto/bee2evp), которая встравивается в библиотеку OpenSSL и работает в связке с ней.

Мы ведем разработку еще одной надстройки на Bee2  -- библиотеки [Bee2j](https://github.com/bcrypto/bee2j), которая будет встраиваться в фреймворки Java, в том числе те из них, которые отвечают за управление расширенными подписями.

**Comment by avodonosov** [comment]
Хоть автор вопроса, вероятно, имел в виду именно испльзование bee2 реализации, но вопрос сформулирован как "с этими алгоритмами",  поэтому добавлю, что коммерческие решения, типа Авест, реализуют те же алгоритмы. Криптопровайдер Авест может использоваться сторонними приложениями через Windows Crypto API.
